# Generated by Django 5.0.4 on 2024-06-02 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_profilemodel_alter_appointmentmodel_patient_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecordmodel',
            options={'verbose_name': 'Медицинская карта', 'verbose_name_plural': 'Медицинские карты'},
        ),
        migrations.AlterModelOptions(
            name='schedulemodel',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.AlterModelOptions(
            name='visitmodel',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterField(
            model_name='medicalrecordmodel',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='medicalrecordmodel',
            name='diagnosis',
            field=models.TextField(verbose_name='Диагноз'),
        ),
        migrations.AlterField(
            model_name='medicalrecordmodel',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.doctormodel', verbose_name='Доктор'),
        ),
        migrations.AlterField(
            model_name='medicalrecordmodel',
            name='last_update_date',
            field=models.DateField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='medicalrecordmodel',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.profilemodel', verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='medicalrecordmodel',
            name='prescription',
            field=models.TextField(verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='medicalrecordmodel',
            name='visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.visitmodel', verbose_name='Визит'),
        ),
    ]
