# Generated by Django 5.0.4 on 2024-06-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_medicalrecordmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulemodel',
            name='date',
        ),
        migrations.AddField(
            model_name='schedulemodel',
            name='day_of_week',
            field=models.CharField(default='Понедельник', max_length=20),
        ),
    ]
