# Generated by Django 5.0.4 on 2024-06-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_schedulemodel_date_schedulemodel_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulemodel',
            name='doctor',
        ),
        migrations.AddField(
            model_name='schedulemodel',
            name='doctor',
            field=models.ManyToManyField(blank=True, to='mainapp.doctormodel'),
        ),
    ]
