# Generated by Django 5.0.4 on 2024-06-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_schedulemodel_doctor_schedulemodel_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Фотография'),
        ),
    ]
