# Generated by Django 5.0.4 on 2024-06-03 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_profilemodel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='photo',
        ),
        migrations.AddField(
            model_name='visitmodel',
            name='visit_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
